---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
useCache: true
useGitignore: true
dictionaryDefinitions:
  - name: cspell-words
    path: cspell-words.txt
    addWords: true
dictionaries:
  - cspell-words
  - python
  - typescript
language: en-US
ignorePaths:
  - '**/*.d.ts'
  - '/.vscode/'
  - '/LICENSE'
  - '/public/'
  - '/vue_app/src/api/'
  - 'biome.json'
  - 'cspell-words.txt'
  - 'cspell.config.yaml'
  - 'package*.json'
  - 'pnpm-lock.yaml'
  - 'pnpm-workspace.yaml'
  - 'uv.lock'

