onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - cypress
  - esbuild

overrides:
  minimatch@>=10.0.0 <10.2.1: '>=10.2.1'
  minimatch@>=10.0.0 <10.2.3: '>=10.2.3'
  serialize-javascript@<7.0.5: '>=7.0.5'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  smol-toml@<1.6.1: '>=1.6.1'
  uuid@<14.0.0: '>=14.0.0'
