// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client/index.js'
import { client } from './client.gen.js'
import type {
  GetAllStatsApiStatsGetData,
  GetAllStatsApiStatsGetResponses,
  GetConfigApiConfigGetData,
  GetConfigApiConfigGetErrors,
  GetConfigApiConfigGetResponses,
  HealthHealthGetData,
  HealthHealthGetResponses,
  ImproveTextApiTextPostData,
  ImproveTextApiTextPostErrors,
  ImproveTextApiTextPostResponses,
  LoginApiAuthLoginPostData,
  LoginApiAuthLoginPostErrors,
  LoginApiAuthLoginPostResponses,
  RootGetData,
  RootGetResponses
} from './types.gen.js'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Login
 *
 * Authenticate user with secret and return JWT token.
 *
 * Rate limited
 *
 * Args:
 * request: FastAPI request object (for rate limiting)
 * login_request: Login credentials containing secret
 *
 * Returns:
 * TokenResponse: JWT token
 *
 * Raises:
 * HTTPException: If credentials are invalid or rate limit exceeded
 */
export const loginApiAuthLoginPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginApiAuthLoginPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    LoginApiAuthLoginPostResponses,
    LoginApiAuthLoginPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * Get Config
 *
 * Get application configuration.
 *
 * Args:
 * provider: Optional provider to get config for, defaults to default provider
 *
 * Returns:
 * ConfigResponse: Current LLM provider, available models, and all providers
 */
export const getConfigApiConfigGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetConfigApiConfigGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetConfigApiConfigGetResponses,
    GetConfigApiConfigGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/config/',
    ...options
  })

/**
 * Improve Text
 *
 * Improve text using AI based on the selected mode.
 */
export const improveTextApiTextPost = <ThrowOnError extends boolean = false>(
  options: Options<ImproveTextApiTextPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ImproveTextApiTextPostResponses,
    ImproveTextApiTextPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/text/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  })

/**
 * Get All Stats
 *
 * Get usage statistics (daily and total).
 *
 * - Admin (user_id=1): Returns stats for all users
 * - Non-admin: Returns stats only for the current user (single row)
 * - PROD: Queries database, Local: Returns mock data with all values set to 0
 *
 * Args:
 * current_user: Authenticated user (injected by dependency)
 *
 * Returns:
 * UsageStatsResponse: Daily and total usage statistics
 */
export const getAllStatsApiStatsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllStatsApiStatsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetAllStatsApiStatsGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/stats/',
    ...options
  })

/**
 * Root
 *
 * Root endpoint.
 */
export const rootGet = <ThrowOnError extends boolean = false>(
  options?: Options<RootGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/',
    ...options
  })

/**
 * Health
 *
 * Health check endpoint.
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthHealthGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health',
    ...options
  })
