// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}/be/korrekturleser-fastapi` | (string & {})
}

/**
 * ConfigResponse
 *
 * Configuration response schema.
 */
export type ConfigResponse = {
  /**
   * Provider
   */
  provider: string
  /**
   * Providers
   *
   * List of available providers
   */
  providers: Array<string>
  /**
   * Models
   *
   * List of available models
   */
  models: Array<string>
}

/**
 * DailyUsage
 *
 * Daily usage statistics.
 */
export type DailyUsage = {
  /**
   * Date
   */
  date: string
  /**
   * User Name
   */
  user_name: string
  /**
   * Cnt Requests
   */
  cnt_requests: number
  /**
   * Cnt Tokens
   */
  cnt_tokens: number
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * LoginRequest
 *
 * Login request schema.
 */
export type LoginRequest = {
  /**
   * Secret
   *
   * User secret
   */
  secret: string
}

/**
 * TextRequest
 *
 * Text improvement request schema.
 */
export type TextRequest = {
  /**
   * Text
   *
   * Text to improve
   */
  text: string
  /**
   * Mode
   *
   * AI text operation mode
   */
  mode: 'correct' | 'improve' | 'summarize' | 'expand' | 'translate_de' | 'translate_en' | 'custom'
  /**
   * Custom Instruction
   *
   * Custom instruction for 'custom' mode
   */
  custom_instruction?: string | null
  /**
   * Provider
   *
   * LLM provider to use (optional, defaults to default provider)
   */
  provider?: string | null
  /**
   * Model
   *
   * LLM model to use (optional, defaults to first available)
   */
  model?: string | null
}

/**
 * TextResponse
 *
 * Text improvement response schema.
 */
export type TextResponse = {
  /**
   * Text Original
   */
  text_original: string
  /**
   * Text Ai
   */
  text_ai: string
  /**
   * Mode
   */
  mode: 'correct' | 'improve' | 'summarize' | 'expand' | 'translate_de' | 'translate_en' | 'custom'
  /**
   * Tokens Used
   */
  tokens_used: number
  /**
   * Model
   */
  model: string
  /**
   * Provider
   */
  provider: string
}

/**
 * TokenResponse
 *
 * Token response schema.
 */
export type TokenResponse = {
  /**
   * Access Token
   */
  access_token: string
  /**
   * Token Type
   */
  token_type?: string
}

/**
 * TotalUsage
 *
 * Total usage statistics.
 */
export type TotalUsage = {
  /**
   * User Name
   */
  user_name: string
  /**
   * Cnt Requests
   */
  cnt_requests: number
  /**
   * Cnt Tokens
   */
  cnt_tokens: number
}

/**
 * UsageStatsResponse
 *
 * Usage statistics response.
 */
export type UsageStatsResponse = {
  /**
   * Daily
   */
  daily: Array<DailyUsage>
  /**
   * Total
   */
  total: Array<TotalUsage>
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
  /**
   * Input
   */
  input?: unknown
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown
  }
}

export type LoginApiAuthLoginPostData = {
  body: LoginRequest
  path?: never
  query?: never
  url: '/api/auth/login'
}

export type LoginApiAuthLoginPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type LoginApiAuthLoginPostError =
  LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors]

export type LoginApiAuthLoginPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse
}

export type LoginApiAuthLoginPostResponse =
  LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses]

export type GetConfigApiConfigGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Provider
     */
    provider?: string | null
  }
  url: '/api/config/'
}

export type GetConfigApiConfigGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetConfigApiConfigGetError =
  GetConfigApiConfigGetErrors[keyof GetConfigApiConfigGetErrors]

export type GetConfigApiConfigGetResponses = {
  /**
   * Successful Response
   */
  200: ConfigResponse
}

export type GetConfigApiConfigGetResponse =
  GetConfigApiConfigGetResponses[keyof GetConfigApiConfigGetResponses]

export type ImproveTextApiTextPostData = {
  body: TextRequest
  path?: never
  query?: never
  url: '/api/text/'
}

export type ImproveTextApiTextPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ImproveTextApiTextPostError =
  ImproveTextApiTextPostErrors[keyof ImproveTextApiTextPostErrors]

export type ImproveTextApiTextPostResponses = {
  /**
   * Successful Response
   */
  200: TextResponse
}

export type ImproveTextApiTextPostResponse =
  ImproveTextApiTextPostResponses[keyof ImproveTextApiTextPostResponses]

export type GetAllStatsApiStatsGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/stats/'
}

export type GetAllStatsApiStatsGetResponses = {
  /**
   * Successful Response
   */
  200: UsageStatsResponse
}

export type GetAllStatsApiStatsGetResponse =
  GetAllStatsApiStatsGetResponses[keyof GetAllStatsApiStatsGetResponses]

export type RootGetData = {
  body?: never
  path?: never
  query?: never
  url: '/'
}

export type RootGetResponses = {
  /**
   * Response Root  Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type RootGetResponse = RootGetResponses[keyof RootGetResponses]

export type HealthHealthGetData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type HealthHealthGetResponses = {
  /**
   * Response Health Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses]
